// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tltdghkyunvhayvxtudq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsdGRnaGt5dW52aGF5dnh0dWRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTY2NjMsImV4cCI6MjA3MTM3MjY2M30.re7weefgeR4pbIm-JFuSWkJSnhfLZ_iHEwmqzt6fnZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});